name: Lint, test and build
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Static Code Analysis
        uses: codacy/codacy-analysis-cli-action@master
      - name: Use Bun 1.0.30
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.30
      - name: Install deps
        run: |
          bun install --frozen-lockfile
          bun x playwright install
      - name: Lint
        run: bun run lint
      - name: Build
        run: bun run build
      - name: Test
        run: bun run test --coverage
      - name: Upload coverage on Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
